---
title: "Scenario Runs"
author: "Seleni Cruz"
date: "February 12, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, include=FALSE}
library(tidyverse)
library(dplyr)
library(datalimited2)
```

#Run CMSY2 for 12 Genus 
```{r}
genus_catch<-read.csv(here::here("data", "function_inputs", "catch_Genus.csv"))%>%
  filter(!(Ano==2000))%>%
   filter(Genus == "Atrina"
        |Genus == "Callinectes"
        |Genus == "Octopus"
        |Genus == "Panulirus"
        |Genus == "Cephalopholis"
        |Genus == "Dasyatis"
        |Genus == "Epinephelus"
        |Genus == "Lutjanus"
        |Genus == "Micropogonias"
        |Genus == "Mugil"
        |Genus == "Scomberomorus"
        |Genus == "Squatina"
        )
genus_priors<-read.csv(here::here("data", "function_inputs", "Genus_priors.csv"))

Genus<-Species_CMSY2(data=genus_catch, priors=genus_priors)
Genus_pts <- Genus[[1]]
Genus_ts<- Genus[[2]]

write.csv(Genus_pts, "Genus_pts.csv")
write.csv(Genus_ts, "Genus_ts.csv")
```




```{r}
#mrate 
mrate <- read.csv(here::here("raw_data", "mrate.csv"))

#variables from CMSY2
pts <- read.csv(here::here("Scenarios", "Genus_pts.csv"))%>%
  merge(mrate, by="Name")%>%
  select(Name, Adjusted, r, r.low, r.hi, k, k.low, k.hi, f, f_lo, f_hi, b, b_lo, b_hi, m.rate, msy, msy.low, msy.hi, bmsy, bmsy.low, bmsy.hi, fmsy, fmsy_lo, fmsy_hi)

#2018 prices
price <- read.csv(here::here("raw_data", "MarketPrice.csv"))

#open access equilibrium at 30%
data.0.3 <- merge(pts, price, by="Name")%>%
  mutate (f_bar = 2 * (1- 0.3/2),
          c = (p * f_bar * 0.3 *msy)/(fmsy * f_bar), 
          c.lo = (p.lo * f_bar * 0.3 *msy.low)/(fmsy_lo * f_bar), 
          c.hi = (p.hi * f_bar * 0.3 *msy.hi)/(fmsy_hi * f_bar), 
          profit.msy = p * msy - (c* fmsy), 
          profit.msy.lo = p.lo * msy.low - (c.lo * fmsy_lo),
          profit.msy.hi = p.hi * msy.hi - (c.hi * fmsy_hi))

write.csv(data.0.3, "input.data.0.3.csv")
```

```{r}
data.0.3 <- read.csv(here::here("Scenarios", "input.data.0.3.csv"))
MPA <- as.matrix(read.csv(here::here("data", "MPA.matrix.csv")))

BAU <-Biological.Model(df=data.0.3, years=100, MPA.mat = MPA, start.year=0)
BAU <- BAU%>%
  mutate(Reserve_size = "BAU")%>%
  filter(!(Adjusted == "IUU_20_legal" | Adjusted == "IUU_40_legal" | Adjusted == "IUU_60_legal"))

MPA_2015 <- Biological.Model(df=data.0.3, years=100, MPA.mat = MPA, start.year=2015)
MPA_2020 <- Biological.Model(df=data.0.3, years=100, MPA.mat = MPA, start.year=2020)
MPA_2025 <- Biological.Model(df=data.0.3, years=100, MPA.mat = MPA, start.year=2025)
MPA_2030 <- Biological.Model(df=data.0.3, years=100, MPA.mat = MPA, start.year=2030)

five_percent<- rbind(MPA_2015, MPA_2020, MPA_2025, MPA_2030)%>%
  mutate(Reserve_size = "5%")

```

```{r}
MPA20<- matrix(ncol=106, nrow=106, 1)
MPA20[sample(106*106, (106*106*0.2))] <- 0

write.csv(MPA20, "MPA20.mat.csv")

MPA_2015 <- Biological.Model(df=data.0.3, years=100, MPA.mat = MPA20, start.year=2015)
MPA_2020 <- Biological.Model(df=data.0.3, years=100, MPA.mat = MPA20, start.year=2020)
MPA_2025 <- Biological.Model(df=data.0.3, years=100, MPA.mat = MPA20, start.year=2025)
MPA_2030 <- Biological.Model(df=data.0.3, years=100, MPA.mat = MPA20, start.year=2030)

twenty_percent<- rbind(MPA_2015, MPA_2020, MPA_2025, MPA_2030)%>%
  mutate(Reserve_size = "20%")
```

```{r}
MPA40<- MPA20
MPA40[sample(106*106, (106*106*0.25))] <- 0

table(MPA40)

write.csv(MPA40, "MPA40.mat.csv")

MPA_2015<-Biological.Model(df=data.0.3, years=100, MPA.mat = MPA40, start.year=2015)
MPA_2020<-Biological.Model(df=data.0.3, years=100, MPA.mat = MPA40, start.year=2020) 
MPA_2025<-Biological.Model(df=data.0.3, years=100, MPA.mat = MPA40, start.year=2025)
MPA_2030<-Biological.Model(df=data.0.3, years=100, MPA.mat = MPA40, start.year=2030)

forty_percent<- rbind(MPA_2015, MPA_2020, MPA_2025, MPA_2030)%>%
  mutate(Reserve_size = "40%")
```

```{r}
MPA_size <- rbind(BAU, five_percent, twenty_percent, forty_percent)%>%
write.csv("PatchModel_size.csv")
```

