---
title: "Report Pots"
author: "Seleni Cruz"
date: "February 13, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE, message=FALSE}
library(ggplot2)
library(here)
library(plotly)
library(tidyverse)
library(gganimate)
library(ggrepel)
library(ggridges)
```

#importing the dataset only looking at 2015-2050
```{r}
res<-read.csv(here::here("Scenarios", "PatchModel_size.csv"))%>%
  filter(Year <= 2050 & Adjusted== "MT")
bmsy<- expression(paste(B/B[MSY]))
fmsy <- expression(paste(F/F[MSY]))

```

```{r}
initial <- res%>%
  filter(Year == 2015 & Status == 0 & Total_Area=="5%")%>%
  mutate(Status = "initial")

initial <- ggplot(initial, aes(x= bbmsy, y=ffmsy, size=Catch_est))+
  geom_rect(xmin = 0.0, xmax = 1.0, ymin = 0.0, ymax = 1, fill = 'yellow', alpha = 0.1) +
  geom_rect(xmin = 0, xmax = 1, ymin = 1.0, ymax = 2.1, fill = 'red', alpha = 0.1) +
  geom_rect(xmin = 1, xmax = 1.5, ymin = 0, ymax = 1, fill = 'green', alpha = 0.1) +
  geom_rect(xmin = 1, xmax = 2.1, ymin = 1, ymax = 2.1, fill = 'orange', alpha = 0.1)+
  geom_point()+
  scale_size(range = c(3, 10))+
  labs(x=bmsy, y=fmsy, title = "Initial Fisheries Status: 2015")+
  geom_vline(xintercept = 1, linetype="dotted", color="black") +
  geom_hline(yintercept = 1, linetype="dotted", color="black") +
  theme_classic(base_size = 18)
initial
ggsave("initial.jpg", width=8, height=5, dpi=300)
```


#1. Kobe plot in Open Access B/Bmsy 0.3

```{r}
initial <- res%>%
  filter(Year == 2015 & Status == 0)%>%
  mutate(Status = "initial")

plot<-res%>%
  filter(Year== 2050 & Total_Area == "5%")%>%
  rbind(initial)

plot$Status<- as.factor(plot$Status)

KobeOA <- ggplot(plot, aes(x= bbmsy, y=ffmsy, group=Name))+
  geom_point(size=3, aes(color= Status, shape=Status))+
  #scale_shape_manual(values=c(16, 17, ))+
  labs(title= "Fishery Status with Reserve Implementation at each Scenario",subtitle = "5% of Total Area" , x=bmsy, y=fmsy)+
  geom_vline(xintercept = 1, linetype="dotted", color="black") +
  geom_hline(yintercept = 1, linetype="dotted", color="black") +
  theme_classic(base_size = 12)
KobeOA
ggsave("KobeOA.jpg", width=8, height=5, dpi=300)

OA <-res%>%
  filter(Status=="2015")
OA$Status<- as.factor(OA$Status)
OA$Name<- as.factor(OA$Name)

KobeOA_size<-ggplot(OA, aes(x= bbmsy, y=ffmsy, group=Name))+
  geom_point(size=2, aes(color=Year, shape=Total_Area))+
  #scale_shape_manual(values=c(16, 17))+
  labs(title= "Fishery Status at various MPA Sizes", subtitle = "2015-2050", x=bmsy, y=fmsy)+
  geom_vline(xintercept = 1, linetype="dotted", color="black") +
  geom_hline(yintercept = 1, linetype="dotted", color="black") +
  theme_classic(base_size = 18)

KobeOA_size<- KobeOA_size+
   facet_wrap(~ Name, ncol=4)
KobeOA_size
ggsave("KobeOA_byMRSize.jpg", width=20, height=15, dpi=300)

```

#FMSY Kobe Plot

```{r}
fmsy<- read.csv(here::here("Scenarios", "PatchModel_FMSY.csv"))%>%
  filter(Adjusted=="MT")

initial <- res%>%
  filter(Year == 2015 & Status == 0 & Total_Area=="5%")%>%
  mutate(Status = "initial")

plot<-fmsy%>%
  filter(Year== 2050 & Total_Area == "5%")%>%
  rbind(initial)

FMSY<-ggplot(plot, aes(x= bbmsy, y=ffmsy, group=Name))+
  geom_point(size=3, aes(shape=Status, color=Status))+
  #scale_shape_manual(values=c(16, 17))+
  labs(title= "Fishery Status when F=Fmsy", subtitle = "2015-2050: 5% Total Area", x=bmsy, y=fmsy)+
  geom_vline(xintercept = 1, linetype="dotted", color="black") +
  geom_hline(yintercept = 1, linetype="dotted", color="black") +
  theme_classic(base_size = 18)
FMSY
ggsave("KobeFMSY.jpg", width=8, height=5, dpi=300)
FMSY<- FMSY+
   facet_wrap(~ Name, ncol=3)
FMSY
ggsave("KobeFMSY_byGenus.jpg", width=10, height=12, dpi=300)
```

```{r}
plot<-res%>%
  filter(Year== 2050)%>%
  rbind(initial)

kobe2<- ggplot(plot, aes(x= bbmsy, y=ffmsy, group= Name))+
  geom_point(size=3, aes(color=Name, shape = Status))+
  #scale_shape_manual(values=c(16, 17, ))+
  labs(title= "Fishery Status with Reserve Implementation", x=bmsy, y=fmsy)+
  geom_vline(xintercept = 1, linetype="dotted", color="black") +
  geom_hline(yintercept = 1, linetype="dotted", color="black") +
  theme_classic(base_size = 18)
kobe2<- kobe2 +
    facet_wrap(~ Total_Area, ncol=2)
kobe2

ggsave("Kobe2.jpg", width=10, height=12, dpi=300)

kobe3<- ggplot(plot, aes(x= bbmsy, y=ffmsy, group= Name))+
  geom_point(size=3, aes(color=Name, shape = Total_Area))+
  #scale_shape_manual(values=c(16, 17, ))+
  labs(title= "Fishery Status with Reserve Implementation" , x=bmsy, y=fmsy)+
  geom_vline(xintercept = 1, linetype="dotted", color="black") +
  geom_hline(yintercept = 1, linetype="dotted", color="black") +
  theme_classic(base_size = 18)
kobe3<- kobe3 +
    facet_wrap(~ Status, ncol=2)
kobe3

ggsave("Kobe3.jpg", width=10, height=12, dpi=300)


```

