---
title: "Graph MPA patch model output"
author: "Seleni Cruz"
date: "January 7, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, echo=FALSE}
library(dplyr)
library(here)
library(ggplot2)
library(plotly)
```


#Biomass projection when catch data was not inflated

```{r, echo=FALSE,  message=FALSE, }
Genus<-read.csv(here::here("data", "Genus_patchmodel.csv"))%>%
  filter(Adjusted=="MT")

graph1<-ggplot(Genus, aes(x=Year, y=Biomass_est, color=Status))+
 geom_line(size=1)+
  #geom_point()+
  labs(x="Year", y="Biomass (MT)", title="Biomass by Genera 2015-2035")+
  theme_classic()+
  scale_x_continuous(expand=c(0,0))+
  scale_y_continuous(expand=c(0,0))+
  theme(legend.title=element_blank())

graph2<-graph1+
   facet_wrap(~ Name, scales = "free_y", ncol=2)

```

```{r, fig.height= 20, fig.width=10}
ggplotly(graph2)
```

#Biomass projection when catch data was inflated 20%
```{r, echo=FALSE,  message=FALSE, }
Genus<-read.csv(here::here("data", "Genus_patchmodel.csv"))%>%
  filter(Adjusted=="MT_20")

graph1<-ggplot(Genus, aes(x=Year, y=Biomass_est, color=Status))+
 geom_line(size=1)+
  #geom_point()+
  labs(x="Year", y="Biomass (MT)", title="Biomass by Genera 2015-2035")+
  theme_classic()+
  scale_x_continuous(expand=c(0,0))+
  scale_y_continuous(expand=c(0,0))+
  theme(legend.title=element_blank())

graph2<-graph1+
   facet_wrap(~ Name, scales = "free_y", ncol=2)

```

```{r, fig.height= 20, fig.width=10}
ggplotly(graph2)
```

#Biomass projection when catch data was inflated 40%

```{r, echo=FALSE,  message=FALSE, }
Genus<-read.csv(here::here("data", "Genus_patchmodel.csv"))%>%
  filter(Adjusted=="MT_40")

graph1<-ggplot(Genus, aes(x=Year, y=Biomass_est, color=Status))+
 geom_line(size=1)+
  #geom_point()+
  labs(x="Year", y="Biomass (MT)", title="Biomass by Genera 2015-2035")+
  theme_classic()+
  scale_x_continuous(expand=c(0,0))+
  scale_y_continuous(expand=c(0,0))+
  theme(legend.title=element_blank())

graph2<-graph1+
   facet_wrap(~ Name, scales = "free_y", ncol=2)

```

```{r, fig.height= 20, fig.width=10}
ggplotly(graph2)
```

#Biomass projection when catch data was inflated 60%

```{r, echo=FALSE,  message=FALSE, }
Genus<-read.csv(here::here("data", "Genus_patchmodel.csv"))%>%
  filter(Adjusted=="MT_60")

graph1<-ggplot(Genus, aes(x=Year, y=Biomass_est, color=Status))+
 geom_line(size=1)+
  #geom_point()+
  labs(x="Year", y="Biomass (MT)", title="Biomass by Genera 2015-2035")+
  theme_classic()+
  scale_x_continuous(expand=c(0,0))+
  scale_y_continuous(expand=c(0,0))+
  theme(legend.title=element_blank())

graph2<-graph1+
   facet_wrap(~ Name, scales = "free_y", ncol=2)

```

```{r, fig.height= 20, fig.width=10}
ggplotly(graph2)
```

