---
title: "MPA Model Run Clean"
author: "Seleni Cruz"
date: "December 10, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(dplyr)
library(here)
library(tidyverse)
```

#Run CMSY2 for 13 Genus 
```{r}
genus_catch<-read.csv(here::here("data", "function_inputs", "catch_Genus.csv"))%>%
   filter(Genus== "Atrina"
        |Genus=="Octopus"
        |Genus=="Callinectes"
        |Genus=="Scomberomorus"
        |Genus=="Epinephelus"
        |Genus=="Mugil"
        |Genus=="Panulirus"
        |Genus=="Cephalopholis"
        |Genus=="Dasyatis"
        |Genus=="Micropogonias"
        |Genus=="Lutjanus"
        |Genus=="Squatina"
        |Genus=="Sphoeroides")

genus_priors<-read.csv(here::here("data", "function_inputs", "Genus_priors.csv"))%>%
   filter(Genus== "Atrina"
        |Genus=="Octopus"
        |Genus=="Callinectes"
        |Genus=="Scomberomorus"
        |Genus=="Epinephelus"
        |Genus=="Mugil"
        |Genus=="Panulirus"
        |Genus=="Cephalopholis"
        |Genus=="Dasyatis"
        |Genus=="Micropogonias"
        |Genus=="Lutjanus"
        |Genus=="Squatina"
        |Genus=="Sphoeroides")

Genus<-Species_CMSY2(data=genus_catch, priors=genus_priors)
Genus_pts <- Genus[1]
Genus_ts<- Genus[2]

write.csv(Genus_pts, "Genus_pts.csv")
write.csv(Genus_ts, "Genus_ts.csv")

```

```{r}
#variables from CMSY2
pts<-read.csv(here::here("data", "Genus_pts.csv"))%>%
  select(Name, Adjusted, r, r.low, r.hi, k, k.low, k.hi, f, f_lo, f_hi, b, b_lo, b_hi, m.rate, msy, msy.low, msy.hi, bmsy, bmsy.low, bmsy.hi, fmsy, fmsy_lo, fmsy_hi)

#2018 prices
price <- read.csv(here::here("raw_data", "MarketPrice.csv"))

#open access equilibrium at 30%
data.0.3<- merge(pts, price, by="Name")%>%
  mutate (c = 0.3 * p * msy / r, 
          c.lo = 0.3 * p.lo * msy.low / r.low, 
          c.hi = 0.3 * p.hi * msy.hi / r.hi, 
          profit.msy = p * msy - (c* r), 
          profit.msy.lo = p.lo * msy.low - (c.lo * r.low),
          profit.msy.hi = p.hi * msy.hi - (c.hi * r.hi))

#open access equilibrium at 10%
data.0.1<- merge(pts, price, by="Name")%>%
  mutate (c = 0.1 * p * msy / r, 
          c.lo = 0.1 * p.lo * msy.low / r.low, 
          c.hi = 0.1 * p.hi * msy.hi / r.hi, 
          profit.msy = p * msy - (c* r), 
          profit.msy.lo = p.lo * msy.low - (c.lo * r.low),
          profit.msy.hi = p.hi * msy.hi - (c.hi * r.hi))

#open access equilibrium at 10%
data.0<- merge(pts, price, by="Name")%>%
  mutate (c = 0 * p * msy / r, 
          c.lo = 0 * p.lo * msy.low / r.low, 
          c.hi = 0 * p.hi * msy.hi / r.hi, 
          profit.msy = p * msy - (c* r), 
          profit.msy.lo = p.lo * msy.low - (c.lo * r.low),
          profit.msy.hi = p.hi * msy.hi - (c.hi * r.hi))

write.csv(data.0.1, "input.data.0.1.csv") 
write.csv(data.0.3, "input.data.0.3.csv")
write.csv(data.0, "input.data.0.csv")
```



#Biologial Patch model for 14 Genus projecting 2016-2035
```{r}
data.0.3<- read.csv(here::here("data", "input.data.0.3.csv"))

data.0.1 <- read.csv(here::here("data", "input.data.0.1.csv"))

data.0 <- read.csv(here::here("data", "input.data.0.csv"))

MPA.mat<-as.matrix(read.csv(here::here("data", "MPA.matrix.csv")))

MPA<-Biological.Model(df=data.0, years=20, MPA.mat = MPA.mat, MPA=1, start.year=0)
No_MPA<-Biological.Model(df=data.0, years=20, MPA.mat = MPA.mat, MPA=0, start.year=0)

MPA_2020<-Biological.Model(df=data.0, years=20, MPA.mat = MPA.mat, MPA=0, start.year=2020) #set MPA to 0, when it hits 2019 it will turn MPA areas to 0 fishing mortality 

MPA_2025<-Biological.Model(df=data.0, years=20, MPA.mat = MPA.mat, MPA=0, start.year=2025)

MPA_2015<- MPA%>%
  mutate(Status="MPA 2015")

MPA_2020<- MPA_2020%>%
  mutate(Status="MPA 2020")

MPA_2025<- MPA_2025%>%
  mutate(Status="MPA 2025")

NO_MPA<- No_MPA%>%
  mutate(Status="No MPA")

patchmodel<- rbind(MPA_2015, MPA_2020, MPA_2025, NO_MPA)

write.csv(patchmodel, "Genus_2D_patchmodel0.csv")


```


#Merging with Catch and biomass from 2000-2015
```{r}
patchmodel<-read.csv(here::here("data", "Genus_2D_patchmodel0.1.csv"))%>%
  select("Name", "Adjusted", "Year", "Biomass_est", "Biomass_lo", "Biomass_hi", "Catch_est", "Catch_lo", "Catch_hi", "Status", "Fishing_est")

genus_ts<-read.csv(here::here("data", "Genus_ts.csv"))%>%
  select(Name, Adjusted, year, catch, b, b_lo, b_hi, f)%>%
  mutate(Catch_lo=NA, Catch_hi=NA, Status = "No MPA")

names(genus_ts)[3:8] <- c("Year", "Catch_est", "Biomass_est", "Biomass_lo", "Biomass_hi", "Fishing_est")

genus_ts <- genus_ts[c("Name", "Adjusted", "Year", "Biomass_est", "Biomass_lo", "Biomass_hi", "Catch_est", "Catch_lo", "Catch_hi", "Status", "Fishing_est")]

patch_2000_2035<- rbind(genus_ts, patchmodel)

write.csv(patch_2000_2035, "merged_2D_output0.0.csv")

```



