---
title: "Function CMSY2"
author: "Seleni Cruz"
date: "November 18, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
suppressPackageStartupMessages({
  library(tidyverse)
  library(here)
  library(dplyr)
  library(tidyr)
  library(devtools)
  devtools::install_github("cfree14/datalimited2") 
  library(datalimited2) # Chris Free updated package for CMSY2
})
```


```{r, message=FALSE}
catch_genus<-read.csv(here("docs", "catch_by_genus.csv"))
Genus<-as.vector(unique(catch_genus$Genus))
resilience<-c("Low", "Low", "Medium", "Medium", "Medium", "Medium", "Low", "Medium", "Very low", "Medium", "Medium")
data<-catch_genus%>% filter(Genus=="Anisotremus")
```


#Burrito Grunt 
```{r, message=FALSE}

stock<-function(data, resilience){
  library(magrittr)
  require(datalimited2)
  
  variables <- tibble(r_min = NA,
                      r = NA,
                      r_max = NA,
                      )
  
  year<-as.vector(data$Ano, mode='numeric')
  
  catches<-(data[,4:7])
  
  for (i in colnames(catches)){
    catch=catches[,i]
  
    cmsy <- datalimited2::cmsy2(year=year, catch=catch, resilience = resilience)
    
    out <- tibble(r= cmsy$ref_pts[1,2:4], 
                  k= cmsy$ref_pts[2,2:4],
                  msy= cmsy$ref_pts[3,2:4], 
                  bmsy= cmsy$ref_pts[5,2:4], 
                  cmsy$ref_ts[,] %>% tail(1))
    
    variables <- rbind(variables, out)
  }
  
  variables %<>%
    drop_na()
  
  return(variables)
}

stock(data=data, resilience="Low")

A<-reg$ref_ts[,1:6]%>%mutate(catch=0)%>%data.frame()
```
