---
title: "yellow_snapper_cmsy_free"
author: "Vienna Saccomanno"
date: "November 2, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages}


 suppressPackageStartupMessages({
  library(tidyverse)
  library(here)
  library(ggplot2)
  library(dplyr)
  library(sf)
  library(rfishbase)
  library(plotly)
  library(fishmethods)
  library(devtools)
devtools::install_github("cfree14/datalimited2") 
  library(datalimited2) # Chris Free updated package for CMSY2
})



```

```{r}
#loading catch data of 6 species with more than 5 years of catch data, detailed code for this dataset is in the "landing sites.rmd" in docs 
focalspeciescatch<-read.csv(here("docs", "focalspeciescatch.csv"))

unique(focalspeciescatch$NombreCientifico) #6 species 

#create a new dataframe to isolate your species of interest 
snapper_sp<-focalspeciescatch%>%
  filter(NombreCientifico=="Lutjanus argentiventris")
View(snapper_sp)


#new datafram to isolate catch increase by 20%

#new datafram to isolate catch increase by 40%

#new datafram to isolate catch increase by 60%
```

```{r}
#Plots catch over given years, simply change the name of the dataframe ie "Octopus"
graph_snapper <-ggplot(snapper_sp, aes(x=Ano, y=MT))+
  geom_line(size=1)+
  ggtitle("Snapper Catch")+
  geom_point()+
  geom_line()+
  labs(x="Year", y="Yearly total catch catch (MT)")+
  theme_classic()+
  scale_x_continuous(expand=c(0,0))+
  scale_y_continuous(expand=c(0,0))+
  theme(legend.title=element_blank())

ggplotly(graph_snapper)
```
FAO considers a maximally sustainable fished stock to be between 0.8 and 1.2 BMSY, an overfished stock to be <0.8 BMSY, and an underfished stock to be >1.2 BMSY. For US federally managed fisheries, NOAA reports on what fraction of stocks are overfished (https://www.fisheries.noaa.gov/feature-story/status-stocks-2017), usually defined as being <0.5 BMSY, though the exact ratio differs by region and type of stock

Paper: https://academic.oup.com/icesjms/advance-article/doi/10.1093/icesjms/fsy138/5133277


```{r}

year_snapper<-c(snapper_sp$Ano) #vector of years
catch_snapper<-c(snapper_sp$MT) #vector of catch date 

#reslience = unsure, saying medium, not on fish base or other preliminary searches

# reported catch
snapper_cmsy_free <- cmsy2(year=year_snapper, catch=catch_snapper, resilience = "Medium")
snapper_cmsy_free_plots <- plot_dlm(a)

snapper_cmsy_free$ref_pts
snapper_cmsy_free$ref_ts


#20% increase of reported catch

#40% increase of reported catch

#60% increase of reported catch

```

