---
title: "Aggregated by Genus"
author: "Seleni Cruz"
date: "October 23, 2018"
output:
  pdf_document: default
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, include=FALSE}
suppressPackageStartupMessages({
  library(tidyverse)
  library(here)
   library(tidyr)
  library(ggplot2)
  library(dplyr)
  library(plotly)
  library(reshape)
})
```


```{r, include=FALSE}
LandingSites<- read.csv (here::here("raw_data", "landingsites.csv"))%>%
  filter(Confirmado=="y")

focalgenus<-read.csv(here::here("raw_data", "Genus.csv"))

catch<- readRDS (here::here("raw_data", "conapesca.RDS"))%>%
  filter(Estado=="Baja california"| Estado=="Sonora")%>%
  filter(!(NombrePrincipal=="Macarela"|NombrePrincipal=="Sardina"|NombrePrincipal=="Camaron"|NombrePrincipal=="Corvina"|NombrePrincipal=="Calamar"|NombrePrincipal=="Anchoveta"))%>%
  merge(LandingSites, by="SitioDesembarque")%>%
  tidyr::separate(NombreCientifico,into="Genus", sep=" ", extra='drop', remove=FALSE)%>%
  mutate_at(.vars = "Genus", .funs = gsub, pattern = " spp", replacement = "")%>%
  merge(focalgenus, by="Genus")

catch_genus<-catch%>%
  group_by(Genus, Ano)%>%
  summarize(MT=sum(PesoVivo)/1000)%>%
  mutate(MT_20= MT*1.2, MT_40= MT*1.4, MT_60=MT*1.6)%>%
  filter(length(unique(Ano))>5|length(unique(Ano))==5)%>%
  dplyr::rename(NombreCientifico=Genus)

write.csv(catch_genus, "catch_genus.csv")

detail_genus<-catch%>%
  group_by(Genus, NombreCientifico, Ano)%>%
  summarize(MT=sum(PesoVivo)/1000)%>%
  filter(length(unique(Ano))>5|length(unique(Ano))==5)

summary<-detail_genus%>%
  group_by(Genus)%>%
  summarize(MT=sum(MT), 
            species=length(unique(NombreCientifico)), 
                           years=length(unique(Ano)))

specieslevel<- detail_genus%>%
  group_by(NombreCientifico)%>%
  summarize(MT=sum(MT))

```


```{r, echo=FALSE}

graph1<-ggplot(catch_genus, aes(x=Ano, y=MT, color=NombreCientifico))+
  #tiff('yearly_catch_focal_species.tiff', units="in", width=10, height=5, res=300)+
  geom_line(size=1)+
  geom_point()+
  labs(x="Year", y="Yearly total catch catch (MT)", title="Yearly Catch of Genus after filtering by landing", subtitle= "2000-2015")+
  theme_classic()+
  scale_x_continuous(expand=c(0,0))+
  scale_y_continuous(expand=c(0,0))+
  theme(legend.title=element_blank())

ggplotly(graph1)
```



```{r, fig.width=10, fig.height=12, echo=FALSE}
graph2<-graph1+
   facet_wrap(~ NombreCientifico, scales = "free_y", ncol=2)
  #tiff('cacthbygenus.tiff', units="in", width=10, height=12, res=300)

ggplotly(graph2)
```

```{r, echo=FALSE}
grouper<-catch_genus%>%
  filter(NombreCientifico=="Epinephelus")

ggplot(grouper, aes(x=Ano, y=MT, color=NombreCientifico))+
  geom_line()+
  theme_classic()+
  labs(x="Year", y="Yearly total catch catch (MT)", title="Yearly Catch of two Epinephelus grouper species ", subtitle= "2000-2015")

#ggplotly(grouper)

```

```{r, echo=FALSE}
snapper<-catch_genus%>%
  filter(NombreCientifico=="Lutjanus")

ggplot(snapper, aes(x=Ano, y=MT, color=NombreCientifico))+
  geom_line()+
  theme_classic()+
  labs(x="Year", y="Yearly total catch catch (MT)", title="Yearly Catch of five Lutjanus snapper species ", subtitle= "2000-2015")

#ggplotly(snapper)
```

```{r, echo=FALSE}
grouper2<-catch_genus%>%
  filter(NombreCientifico=="Mycteroperca")

ggplot(grouper2, aes(x=Ano, y=MT, color=NombreCientifico))+
  geom_line()+
  theme_classic()+
  labs(x="Year", y="Yearly total catch catch (MT)", title="Yearly Catch of two Mycteroperca grouper species ", subtitle= "2000-2015")

#ggplotly(grouper2)
```

