---
title: "Cleaning data"
author: "Seleni Cruz"
date: "May 14, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Loading packages
```{r}
suppressPackageStartupMessages({
  library(tidyverse)
  library(here)
  library(ggplot2)
  library(dplyr)
})
```

#Load .RDS file 
Filter national data set to just Sonora and Baja California Sur
```{r}

catch<- readRDS(here("raw_data", "conapesca.RDS"))%>%
  filter(Estado== "Baja california sur"| Estado=="Sonora")

unique(catch$NombreCientifico) #481 species 
unique(catch$LugarDeCaptura) #3914 areas identified 
unique(catch$NombreComun) #925 common names 
unique(catch$NombrePrincipal) #57 principal names

#Can consider further filtering by fishing area "LugarDeCaptura"

mostvaluable<- catch%>%
  group_by(NombrePrincipal, Ano)%>%
  summarise(value=sum(Valor), kg=sum(PesoDesembarcado))%>%
  summarise(usdM=((mean(value)/16)/1000000),avg_kgM=mean(kg)/1000000)%>%
  arrange(desc(usdM))

mostvaluable

otras<-catch%>%
  filter(NombrePrincipal=="Otras") #lots of fin fish, can also use scientific name instead 

write.csv(catch, file = here("data", "clean_landings_data.csv"), row.names = F)
```


