---
title: "Focal Landing Sites"
author: "Seleni Cruz"
date: "October 23, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, include=FALSE}
suppressPackageStartupMessages({
  library(tidyverse)
  library(here)
  library(ggplot2)
  library(dplyr)
  library(sf)
  library(rfishbase)
  library(plotly)
  library(reshape)
})
```

###Load Catch data and list of focal species
Filter national data set to just Sonora and Baja California and exclude industrial species 
```{r, include=FALSE}
#Load Conapedsca Catch data and filter national data set to just Sonora and Baja California and exclude industrial species
catch<- readRDS (here("raw_data", "conapesca.RDS"))%>%
  filter(Estado=="Baja california"| Estado=="Sonora")%>%
   filter(!(NombrePrincipal=="Macarela"|NombrePrincipal=="Sardina"|NombrePrincipal=="Camaron"|NombrePrincipal=="Corvina"|NombrePrincipal=="Calamar"|NombrePrincipal=="Anchoveta"))

#Load focal species
focalspecies<-read.csv(here("raw_data", "finalfocalspecies.csv"))

#loading landing sites verified by Eda 
LandingSites<- read.csv (here("raw_data", "landingsites.csv"))%>%
  filter(Confirmado=="y")  #29 landing sites 


#merge catch with landing sites and calculate weight in metric tons 
focal_landing<-merge(catch, LandingSites, by = "SitioDesembarque")%>%
  group_by(NombreCientifico, Ano)%>% 
  summarize(MT=sum(PesoVivo)/1000)

unique(focal_landing$NombreCientifico) #163 speices that are landed at 29 landing sites in the MRI

#Calculating total yearly landings of all 163 species every year 
yearlylanding<- focal_landing%>%
  group_by(Ano)%>%
  summarize(yr_land= sum(MT))

mean(yearlylanding$yr_land)

#Calculating total landings for each 163 speies across all years, column years is the number of years for which data is available for that species    
specieslanding<- focal_landing%>%
  group_by(NombreCientifico)%>%
  summarize(sp_land= sum(MT), years=length(unique(Ano)))

#Calculating average landings of species across all years by species 
toplandings<-focal_landing%>%
  group_by(NombreCientifico)%>%
  summarize(avergelandings=mean(MT))%>%
  mutate(percent=(avergelandings/sum(avergelandings)*100))

sum(toplandings$avergelandings)

#Merge catch with focal species by Scientific name 
catchfocalspecies<-merge(catch, focalspecies, by= "NombreCientifico")
unique(catchfocalspecies$NombreCientifico)

#Merge catchfocalspecies with landing sites identifies in BC and Sonora 
focallandingsites<-merge(catchfocalspecies, LandingSites, by= "SitioDesembarque")

#Calculate total catch in the region by year and number of species reported in each year 
spp_catch<-focallandingsites%>%
  group_by(NombreCientifico, Ano)%>%
  summarize(MT=sum(PesoVivo)/1000)%>%
  filter(length(unique(Ano))>5|length(unique(Ano))==5)
unique(spp_catch$NombreCientifico)

write.csv(spp_catch, "focalspeciescatch.csv")

```


```{r, echo=FALSE}

graph5 <-ggplot(spp_catch, aes(x=Ano, y=MT, color=NombreCientifico))+
  #tiff('yearly_catch_focal_species.tiff', units="in", width=10, height=5, res=300)+
  geom_line(size=1)+
  geom_point()+
  labs(x="Year", y="Yearly total catch catch (MT)", title="Yearly Catch of focal species after filtering by landing", subtitle= "2000-2015")+
  theme_classic()+
  scale_x_continuous(expand=c(0,0))+
  scale_y_continuous(expand=c(0,0))+
  theme(legend.title=element_blank())

ggplotly(graph5)


```



```{r, fig.width=8, fig.height=12, echo=FALSE}
graph6<-graph5+
   facet_wrap(~ NombreCientifico, scales = "free_y", ncol=2)

ggplotly(graph6)
```

Total value of landings is $411,467 

```{r}
value2014<-spp_catch%>%
  filter(Ano=="2014")%>%
  merge(focalspecies, by="NombreCientifico")%>%
  mutate(total_min_value_2014=(MT*Min2014*0.053*1000), total_max_value_2014=(MT*Max2014*0.053*1000), total_avg_value_2014=(MT*Average2014*0.053*1000), value_percent=(total_avg_value_2014/sum(total_avg_value_2014)*100))

plot_ly(value2014, labels = ~NombreCientifico, values = ~total_avg_value_2014, type = 'pie', showlegend=FALSE) %>%
  layout(title = 'Revenue generated by focal species in 2014 in USD')

sum(value2014$total_avg_value_2014)
```

