---
title: "MSY"
author: "Seleni Cruz"
date: "October 7, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Packages 

fishlife 
plus one paper 
```{r}
suppressPackageStartupMessages({
  library(tidyverse)
  library(here)
  library(ggplot2)
  library(dplyr)
  library(sf)
  library(rfishbase)
  library(fishmethods)
  library(devtools)
install_github("James-Thorson/FishLife")
library(FishLife)
})


```


#Load catch data of species per year 
```{r}
catch_yr<-read.csv(here("docs", "catch_yr.csv"))%>% 
  filter(NombreCientifico=="Balistes polylepis")
```


#Species parameters as found in fishbase
https://cran.r-project.org/web/packages/rfishbase/rfishbase.pdf

```{r}
#Vector for fishbase package 
fish<-c("Anisotremus interruptus",
"Balistes polylepis",
"Calamus brachysomus",
"Epinephelus analogus",
"Epinephelus labriformis",
"Haemulon flaviguttatum",
"Haemulon scudderi",
"Lutjanus argentiventris",
"Lutjanus guttatus",
"Mycteroperca jordani",
"Mycteroperca prionura",
"Panulirus inflatus",
"Panulirus interruptus",
"Paralabrax auroguttatus",
"Paralabrax maculatofasciatus",
"Pinctada mazatlanica",
"Scarus perrico")

fish

validate_names(fish) #ID possible misspelling, changed names etc 

lifehistory<-popgrowth(fish) #the most useful but most of the data is missing 

?popgrowth

rep<-reproduction(fish)

char<-popchar(fish)
  
spawn<-spawning(fish)

stock<-stocks(fish)
```




#Getting information from Fishlife r package 
```{r}
Plot_taxa( Search_species(Genus="Lutjanus",Species="argentiventris")$match_taxonomy )


vignette("tutorial","FishLife")

Calculate_ratio(params = c("K", "M"), Cov_gjj = FishLife::database$Cov_gjj,
  Mean_gj = FishLife::database$ParHat$beta_gj,
  ParentChild_gz = FishLife::database$ParentChild_gz)

```


#Frist atempt at catchmsy 
```{r}
year<-c(catch_yr$Ano) #vector of years 
catch<-c(catch_yr$Annual_Catch) #vector of catch date 
?catchmsy


trial<-catchmsy(year=year,
                catch=catch,
                catchCV=NULL,#not sure what this is 
                catargs = (dist="none"), 
    l0=list(low=0.3,up=0.3,step=0),#biomass in year 1 in relation to K, step=0 means it will select randomly from the range given assuming normal dist
    lt=list(low=0.01,up=0.25,refyr=2002),sigv=0, #depletion level in year 1; like fishing mortiality?
    k=list(dist="unif",low=20392.8528,up=20392.8528), #carrying capacity; can include mean= and sd=
    r=list(dist="unif",low=0.2178754,up=0.2178754), #intrinsic growth rate
    M=list(dist="unif",low=0.18,up=0.18,mean=0.00,sd=0.00), #Natural mortality 
    nsims=30000, #Monte carlo simulations 
    catchout = (1), #saving the monte carlo simulations that can later be graphed
    grout = 1, #output just to console, 
    graphs = c(1, 2,3,4,5,6,7,8,9,10,11))
trial



```

